/* -- 公共平台-- */

// 首页
export const HOME = 'HOME'
// 用户中心 -- 空白页
export const USERCENTER_WELCOME = 'USERCENTER_WELCOME'
// 消息
export const LABORATORY_NOTICE = 'LABORATORY_NOTICE'
// 用户中心
export const PUBLIC_USER_CENTER__USER_INFO = 'PUBLIC_USER_CENTER__USER_INFO'
// 访问管理
export const PUBLIC_VISIT_MANAGE__USER_CONFIG = 'PUBLIC_VISIT_MANAGE__USER_CONFIG'
export const PUBLIC_VISIT_MANAGE__MANAGE_CONFIG = 'PUBLIC_VISIT_MANAGE__MANAGE_CONFIG'
// 用户管理
export const PUBLIC_USER_MANAGE__MANAGER_LIST = 'PUBLIC_USER_MANAGE__MANAGER_LIST'
// 用户管理/用户列表
export const PUBLIC_USER_MANAGE__USER_LIST = 'PUBLIC_USER_MANAGE__USER_LIST'
// 工厂配置
export const PUBLIC_USER_WORK__FACTORY = 'PUBLIC_USER_WORK__FACTORY'
// 用户管理/工种设置
export const PUBLIC_USER_WORK__TYPE = 'PUBLIC_USER_WORK__TYPE'
// 用户管理/人员信息
export const PUBLIC_USER_PERSERN_INFORMATION = 'PUBLIC_USER_PERSERN_INFORMATION'

// 组织管理
export const PUBLIC_PERMISSION_MANAGE__ORGANIZATION_MANAGE = 'PUBLIC_PERMISSION_MANAGE__ORGANIZATION_MANAGE'
export const PUBLIC_PERMISSION_MANAGE__ROLE_MANAGE = 'PUBLIC_PERMISSION_MANAGE__ROLE_MANAGE'
// 权限管理 --> 权限管理
export const PUBLIC_PERMISSION_MANAGE__PERMISSION_MANAGE = 'PUBLIC_PERMISSION_MANAGE__PERMISSION_MANAGE'
// 权限管理 --> 子系统管理
export const PUBLIC_PERMISSION_MANAGE__SUBSYSTEM_LIST = 'PUBLIC_PERMISSION_MANAGE__SUBSYSTEM_LIST'
// 权限管理 --> 模块管理
export const PUBLIC_PERMISSION_MANAGE__MODULAR_LIST = 'PUBLIC_PERMISSION_MANAGE__MODULAR_LIST'
/* --------------------------------------------------自动化采集--------------------------------------------------- */
// 设备管理 -- 机台档案
export const AUTOMATIC_MACHINE_RECORD = 'AUTOMATIC_MACHINE_RECORD'
// 设备管理 -- 丝机管理
export const AUTOMATIC_EQUIPMENT_FILATURE = 'AUTOMATIC_EQUIPMENT_FILATURE'
// 设备管理 -- 叉车管理
export const AUTOMATIC_EQUIPMENT_FORKLIFT = 'AUTOMATIC_EQUIPMENT_FORKLIFT'
// 设备管理 -- 机台部件
export const AUTOMATIC_MACHINE_PARTS = 'AUTOMATIC_MACHINE_PARTS'
// 设备管理 -- 机台部件类型
export const AUTOMATIC_MACHINE_PARTS_TYPE = 'AUTOMATIC_MACHINE_PARTS_TYPE'

// 人员信息管理 -- 人员信息
export const AUTOMATIC_PERSON_INFORMATION = 'AUTOMATIC_PERSON_INFORMATION'
// 人员信息管理 -- 班次管理
export const AUTOMATIC_PERSON_SCHEDULE = 'AUTOMATIC_PERSON_SCHEDULE'
// 人员信息管理 -- 打卡记录管理
export const AUTOMATIC_PERSON_PUNCH = 'AUTOMATIC_PERSON_PUNCH'
// 人员信息管理 -- 排班管理
export const AUTOMATIC_PERSON_WORKFORCE_MANAGEMENT = 'AUTOMATIC_PERSON_WORKFORCE_MANAGEMENT'

// 库存管理 -- 库房定义
export const AUTOMATIC_INVENTORY_STORAGE = 'AUTOMATIC_INVENTORY_STORAGE'
// 库存管理 -- 库位定义
export const AUTOMATIC_INVENTORY_LIBRARY = 'AUTOMATIC_INVENTORY_LIBRARY'
// 库存管理 -- 库位计划
export const AUTOMATIC_INVENTORY_LIBRARY_PLAY = 'AUTOMATIC_INVENTORY_LIBRARY_PLAY'

// 产品基础信息 -- 降等原因
export const AUTOMATIC_PRODUCT_DOWNGRADE_REASONS = 'AUTOMATIC_PRODUCT_DOWNGRADE_REASONS'
// 产品基础信息 -- 生产计划
export const AUTOMATIC_PRODUCT_PRODUCTION_PLAN = 'AUTOMATIC_PRODUCT_PRODUCTION_PLAN'
// 产品基础信息 -- 线别信息
export const AUTOMATIC_PRODUCT_LINE_INFORMATION = 'AUTOMATIC_PRODUCT_LINE_INFORMATION'

// 数据字典 -- 叉车类型
export const AUTOMATIC_DATA_DICTIONARY_FORKLIFT_TYPE = 'AUTOMATIC_DATA_DICTIONARY_FORKLIFT_TYPE'
// 数据字典 -- 车间
export const AUTOMATIC_DATA_DICTIONARY_WORKSHOP = 'AUTOMATIC_DATA_DICTIONARY_WORKSHOP'
// 数据字典 -- 工种
export const AUTOMATIC_DATA_DICTIONARY_WORK_TYPE = 'AUTOMATIC_DATA_DICTIONARY_WORK_TYPE'
// 数据字典 -- 职位
export const AUTOMATIC_DATA_DICTIONARY_WORK_LEVEL = 'AUTOMATIC_DATA_DICTIONARY_WORK_LEVEL'
// 数据字典 -- 降等原因类别
export const AUTOMATIC_DATA_DICTIONARY_DOWN_REASON_TYPE = 'AUTOMATIC_DATA_DICTIONARY_DOWN_REASON_TYPE'
// 数据字典 -- 产品工艺
export const AUTOMATIC_DATA_DICTIONARY_WORKMANSHIP = 'AUTOMATIC_DATA_DICTIONARY_WORKMANSHIP'
// 产品参数 -- 种类
export const AUTOMATIC_DATA_DICTIONARY_SPECIES = 'AUTOMATIC_DATA_DICTIONARY_SPECIES'
// 数据字典 -- 纸管信息
export const AUTOMATIC_DATA_DICTIONARY_PAPER_TUBE_INFO = 'AUTOMATIC_DATA_DICTIONARY_PAPER_TUBE_INFO'
// 数据字典 -- 丝锭批号
export const AUTOMATIC_DATA_DICTIONARY_SPINDLE_NUM = 'AUTOMATIC_DATA_DICTIONARY_SPINDLE_NUM'
// 数据字典 -- 打印机信息
export const AUTOMATIC_DATA_DICTIONARY_PRINTER_INFO = 'AUTOMATIC_DATA_DICTIONARY_PRINTER_INFO'
// 数据字典 -- 丝锭规格
export const AUTOMATIC_DATA_DICTIONARY_SILK_SPEC = 'AUTOMATIC_DATA_DICTIONARY_SILK_SPEC'
// 数据字典 -- 班次维护
export const AUTOMATIC_DATA_DICTIONARY_CLASS_MAINTAIN = 'AUTOMATIC_DATA_DICTIONARY_CLASS_MAINTAIN'
// 数据字典 -- 丝锭锭重
export const AUTOMATIC_DATA_DICTIONARY_SILK_WEIGHT = 'AUTOMATIC_DATA_DICTIONARY_SILK_WEIGHT'
// 数据字典 -- 产品分类
export const AUTOMATIC_DATA_DICTIONARY_PRODUCT_TYPE = 'AUTOMATIC_DATA_DICTIONARY_PRODUCT_TYPE'
// 数据字典 -- 丝锭等级
export const AUTOMATIC_DATA_DICTIONARY_SILK_GRADE = 'AUTOMATIC_DATA_DICTIONARY_SILK_GRADE'
// 数据字典 -- 异常等级
export const AUTOMATIC_DATA_DICTIONARY_UNUSUAL_GRADE = 'AUTOMATIC_DATA_DICTIONARY_UNUSUAL_GRADE'
// 数据字典 -- 异常等级设置
export const AUTOMATIC_DATA_DICTIONARY_UNUSUAL_GRADE_SET = 'AUTOMATIC_DATA_DICTIONARY_UNUSUAL_GRADE_SET'
// 数据字典 -- 染判等级
export const AUTOMATIC_DATA_DICTIONARY_DYE_LEVEL = 'AUTOMATIC_DATA_DICTIONARY_DYE_LEVEL'
// 数据字典 -- 饶卷备注
export const AUTOMATIC_DATA_DICTIONARY_WIND_REMARK = 'AUTOMATIC_DATA_DICTIONARY_WIND_REMARK'

/* ----------------------------------------------- 车间生产作业 ----------------------------------------------- */
// 生产计划
export const AUTOMATIC_PRODUCT_PRODUCT_PLAN = 'AUTOMATIC_PRODUCT_PRODUCT_PLAN'
// 条码打印
export const AUTOMATIC_PRODUCT_BARCODE_PRINTING = 'AUTOMATIC_PRODUCT_BARCODE_PRINTING'
// 染判
export const AUTOMATIC_PRODUCT_DYE_JUDGE = 'AUTOMATIC_PRODUCT_DYE_JUDGE'
// 物检操作
export const AUTOMATIC_PRODUCT_CHECK_ACTION = 'AUTOMATIC_PRODUCT_CHECK_ACTION'
// 物检备注
export const AUTOMATIC_PRODUCT_CHECK_REMARK = 'AUTOMATIC_PRODUCT_CHECK_REMARK'
// 计量打印
export const AUTOMATIC_PRODUCT_MEASURE_PRINTING = 'AUTOMATIC_PRODUCT_MEASURE_PRINTING'
// 丝锭异常状态
export const AUTOMATIC_PRODUCT_SILK_EXCEPTION = 'AUTOMATIC_PRODUCT_SILK_EXCEPTION'
// 丝锭追踪
export const AUTOMATIC_PRODUCT_SILK_TRACE = 'AUTOMATIC_PRODUCT_SILK_TRACE'
// 丝车状态查询
export const AUTOMATIC_PRODUCT_SILK_CAR_STATE = 'AUTOMATIC_PRODUCT_SILK_CAR_STATE'
// 车间生产状况
export const AUTOMATIC_PRODUCT_PRODUCT_STATE = 'AUTOMATIC_PRODUCT_PRODUCT_STATE'
// 报表管理 -- 产品报表
export const AUTOMATIC_PRODUCT_STATEMENT_PERSONAL_SCANNING_CAPACITY = 'AUTOMATIC_PRODUCT_STATEMENT_PERSONAL_SCANNING_CAPACITY'
// 报表管理 -- 质量报表
export const AUTOMATIC_PRODUCT_STATEMENT_PRODUCTION_YIELD = 'AUTOMATIC_PRODUCT_STATEMENT_PRODUCTION_YIELD'
// 报表管理 -- 异常报表
export const AUTOMATIC_PRODUCT_STATEMENT_EXCEPTION_REPORT = 'AUTOMATIC_PRODUCT_STATEMENT_EXCEPTION_REPORT'
// 报表管理 -- 染色降等比率月报
export const AUTOMATIC_PRODUCT_STATEMENT_MONTHLY_DEGRADATION = 'AUTOMATIC_PRODUCT_STATEMENT_MONTHLY_DEGRADATION'
// 报表管理 -- 同批多线别双A率报表
export const AUTOMATIC_PRODUCT_STATEMENT_LINENUM_PRODUCTION = 'AUTOMATIC_PRODUCT_STATEMENT_LINENUM_PRODUCTION'
// 生产报表 -- 下机产量日报表
export const AUTOMATIC_PRODUCT_STATEMENT_OFFLINE_DAILY_PRODUCTION = 'AUTOMATIC_PRODUCT_STATEMENT_OFFLINE_DAILY_PRODUCTION'
// 标样丝管理
export const AUTOMATIC_PRODUCT_PROTOTYPE_SILK = 'AUTOMATIC_PRODUCT_PROTOTYPE_SILK'
// 异常报警管理
export const AUTOMATIC_SAMPLE_PLATE_MANAGEMENT = 'AUTOMATIC_SAMPLE_PLATE_MANAGEMENT'

// 看板 -- 车间异常看板
export const AUTOMATIC_BOARD_WORKSHOP_ABNORMAL = 'AUTOMATIC_BOARD_WORKSHOP_ABNORMAL'
// 看板 -- 报警看板
export const AUTOMATIC_BOARD_ALARM = 'AUTOMATIC_BOARD_ALARM'
// 看板 -- 自动生产线
export const AUTOMATIC_BOARD_AUTO_LINE = 'AUTOMATIC_BOARD_AUTO_LINE'
// 看板 -- 智能制造中心
export const AUTOMATIC_BOARD_SMART_MANUFACTURING_CENTER = 'AUTOMATIC_BOARD_SMART_MANUFACTURING_CENTER'
// 看板 -- 自动化分析看板
export const AUTOMATIC_BOARD_DASH_BOARD = 'AUTOMATIC_BOARD_DASH_BOARD'
// 计量打印 -- 暂存箱条码
export const AUTOMATIC_PACKAGE_KEEP_BARCODE = 'AUTOMATIC_PACKAGE_KEEP_BARCODE'
// 计量打印 -- 拆包
export const AUTOMATIC_PACKAGE_EXCRETE_PACK = 'AUTOMATIC_PACKAGE_EXCRETE_PACK'
// 生产任务/包装计量/补打唛头
export const AUTOMATIC_PACKAGE_REPAIR_MARK = 'AUTOMATIC_PACKAGE_REPAIR_MARK'
// 生产任务/包装计量/唛头条码
export const AUTOMATIC_PACKAGE_MARK_BAR_CODE = 'AUTOMATIC_PACKAGE_MARK_BAR_CODE'
// 丝锭翻包查询
export const AUTOMATIC_PRODUCT_SILK_PACKAGE_OWNER = 'AUTOMATIC_PRODUCT_SILK_PACKAGE_OWNER'
// 短纤唛头打印
export const AUTOMATIC_PRODUCT_SILK_PRINT = 'AUTOMATIC_PRODUCT_SILK_PRINT'
// 箱包丝锭
export const AUTOMATIC_PRODUCT_BAG_SILK_INGOT = 'AUTOMATIC_PRODUCT_BAG_SILK_INGOT'
// 计量打印 -- 外贸码单
export const AUTOMATIC_EXTERNAL_TRADE_BARCODE = 'AUTOMATIC_EXTERNAL_TRADE_BARCODE'

/* --------------------------------------- 仓库维护 --------------------------------------- */
// 仓库
export const STORAGE__WAREHOUSE_MANAGEMENT__WAREHOUSE = 'STORAGE__WAREHOUSE_MANAGEMENT__WAREHOUSE'
// 车牌
export const STORAGE__WAREHOUSE_MANAGEMENT__PLATE_NUMBER = 'STORAGE__WAREHOUSE_MANAGEMENT__PLATE_NUMBER'
// 叉车
export const STORAGE__WAREHOUSE_MANAGEMENT__FORKLIFT = 'STORAGE__WAREHOUSE_MANAGEMENT__FORKLIFT'
// 叉车状态
export const STORAGE__WAREHOUSE_MANAGEMENT__FORKLIFT_STATUS = 'STORAGE__WAREHOUSE_MANAGEMENT__FORKLIFT_STATUS'
// 退货原因
export const STORAGE__WAREHOUSE_MANAGEMENT__RETURN_REASON = 'STORAGE__WAREHOUSE_MANAGEMENT__RETURN_REASON'
// 装载点
export const STORAGE__WAREHOUSE_MANAGEMENT_LOADING_POINT = 'STORAGE__WAREHOUSE_MANAGEMENT_LOADING_POINT'
// 装运点
export const STORAGE__WAREHOUSE_MANAGEMENT_TRANSPORT_POINT = 'STORAGE__WAREHOUSE_MANAGEMENT_TRANSPORT_POINT'
// 入库规则
export const STORAGE__WAREHOUSE_MANAGEMENT_WAREHOUSING_RULES = 'STORAGE__WAREHOUSE_MANAGEMENT_WAREHOUSING_RULES'
// 物料号查询
export const STORAGE__WAREHOUSE_MANAGEMENT_MATERIALS_SEARCH = 'STORAGE__WAREHOUSE_MANAGEMENT_MATERIALS_SEARCH'
// SAP库位
export const STORAGE__WAREHOUSE_MANAGEMENT_SAP_POSITION = 'STORAGE__WAREHOUSE_MANAGEMENT_SAP_POSITION'
// SAP销售组织
export const STORAGE__WAREHOUSE_MANAGEMENT_SAP_ORGANIZATION = 'STORAGE__WAREHOUSE_MANAGEMENT_SAP_ORGANIZATION'
// SAP状态
export const STORAGE__WAREHOUSE_MANAGEMENT_SAP_STATUS = 'STORAGE__WAREHOUSE_MANAGEMENT_SAP_STATUS'
/* --------------------------------------------------- 仓库管理 -------------------------------------------- */
// 库位计划
export const STORAGE__WAREHOUSE_MANAGEMENT__AREA_PLAN = 'STORAGE__WAREHOUSE_MANAGEMENT__AREA_PLAN'
// 库位视图
export const STORAGE__WAREHOUSE_MANAGEMENT__AREA_VIEW = 'STORAGE__WAREHOUSE_MANAGEMENT__AREA_VIEW'
// 库存明细
export const STORAGE__WAREHOUSE_MANAGEMENT__INVENTORY_DETAIL = 'STORAGE__WAREHOUSE_MANAGEMENT__INVENTORY_DETAIL'
// 库存明细管理
export const STORAGE__WAREHOUSE_MANAGEMENT__INVENTORY_DETAIL_MANAGE = 'STORAGE__WAREHOUSE_MANAGEMENT__INVENTORY_DETAIL_MANAGE'
// 托盘查询
export const STORAGE__WAREHOUSE_MANAGEMENT__SHAREDPALLET_SEARCH = 'STORAGE__WAREHOUSE_MANAGEMENT__SHAREDPALLET_SEARCH'
// 调拨出库
export const STORAGE__WAREHOUSE_MANAGEMENT__ALLOT_OUT = 'STORAGE__WAREHOUSE_MANAGEMENT__ALLOT_OUT'
// 出入库记录
export const STORAGE__WAREHOUSE_MANAGEMENT__OUT_IN_RECORD = 'STORAGE__WAREHOUSE_MANAGEMENT__OUT_IN_RECORD'
// 退货处理
export const STORAGE__WAREHOUSE_MANAGEMENT__RETURN_HANDLE = 'STORAGE__WAREHOUSE_MANAGEMENT__RETURN_HANDLE'
// 散件发运
export const STORAGE__WAREHOUSE_MANAGEMENT__PART_DELIVERY = 'STORAGE__WAREHOUSE_MANAGEMENT__PART_DELIVERY'
// 库间转移
export const STORAGE__WAREHOUSE_MANAGEMENT__STORAGE_MOVE = 'STORAGE__WAREHOUSE_MANAGEMENT__STORAGE_MOVE'
// 入库异常
export const STORAGE__WAREHOUSE_MANAGEMENT__EXCEPTION_HANDLING = 'STORAGE__WAREHOUSE_MANAGEMENT__EXCEPTION_HANDLING'

/* ------------------------------------------ 记录报表 -------------------------------------- */
// 盘点记录
export const STORAGE__WAREHOUSE_MANAGEMENT__CHECK_RECORD = 'STORAGE__WAREHOUSE_MANAGEMENT__CHECK_RECORD'
// 报表
export const STORAGE__WAREHOUSE_MANAGEMENT__REPORT_FORM = 'STORAGE__WAREHOUSE_MANAGEMENT__REPORT_FORM'
// 翻包
export const STORAGE__WAREHOUSE_MANAGEMENT__RUMMAGE_PACKAGE = 'STORAGE__WAREHOUSE_MANAGEMENT__RUMMAGE_PACKAGE'
/** -------------------------------------------------------二期物检---------------------------------------------------------- */
// 数据字典管理
export const LABORATORY_DATAFIELD_MANAGE = 'LABORATORY_DATAFIELD_MANAGE'
// 物检管理/文档管理
export const LABORATORY_PERSONNEL_MANAGEMENT_WORKLOAD_MANEGE = 'LABORATORY_PERSONNEL_MANAGEMENT_WORKLOAD_MANEGE'
// 物检管理/文件分享
export const LABORATORY_PERSONNEL_MANAGEMENT_WORKLOAD_SHARE = 'LABORATORY_PERSONNEL_MANAGEMENT_WORKLOAD_SHARE'
// 物检管理/文档操作
export const LABORATORY_PERSONNEL_MANAGEMENT_WORKLOAD_DONE = 'LABORATORY_PERSONNEL_MANAGEMENT_WORKLOAD_DONE'
// 化检管理/文档管理
export const LABORATORY_PERSONNEL_MANAGEMENT_CHEMICAL_MANEGE = 'LABORATORY_PERSONNEL_MANAGEMENT_CHEMICAL_MANEGE'
// 化检管理/文件分享
export const LABORATORY_PERSONNEL_MANAGEMENT_CHEMICAL_SHARE = 'LABORATORY_PERSONNEL_MANAGEMENT_CHEMICAL_SHARE'
// 化检管理/文件操作
export const LABORATORY_PERSONNEL_MANAGEMENT_CHEMICAL_DONE = 'LABORATORY_PERSONNEL_MANAGEMENT_CHEMICAL_DONE'
// 原始记录单模板分类
export const LABORATORY_ORIGINAL_RECORDLIST_CLASSIFY = 'LABORATORY_ORIGINAL_RECORDLIST_CLASSIFY'
// 原始记录单模板管理
export const LABORATORY_ORIGINAL_RECORDLIST_MANAGE = 'LABORATORY_ORIGINAL_RECORDLIST_MANAGE'
// 样品分组管理
export const LABORATORY_SAMPLE_MANAGE_SPLIT_GROUP = 'LABORATORY_SAMPLE_MANAGE_SPLIT_GROUP'
// 样品登记管理
export const LABORATORY_SAMPLE_MANAGE_REGISTER = 'LABORATORY_SAMPLE_MANAGE_REGISTER'
// 样品
export const LABORATORY_SAMPLE_MANAGE_SAMPLE = 'LABORATORY_SAMPLE_MANAGE_SAMPLE'
// 实验报告单模板分类
export const LABORATORY_REPORTLIST_TEMPLATE_CLASSIFY = 'LABORATORY_REPORTLIST_TEMPLATE_CLASSIFY'
// 实验报告单模板管理
export const LABORATORY_REPORTLIST_TEMPLATE_MANAGE = 'LABORATORY_REPORTLIST_TEMPLATE_MANAGE'
// 二期待实验/手工记录单
export const LABORATORY_SEC_TOBE_LABORATORY = 'LABORATORY_SEC_TOBE_LABORATORY'
// 二期待实验/含油实验任务
export const LABORATORY_SEC_TOBE_CONTAINS_OIL_TASK = 'LABORATORY_SEC_TOBE_CONTAINS_OIL_TASK'
// 二期待实验/报告单
export const LABORATORY_SEC_TOBE_LABORATORY_REPORT = 'LABORATORY_SEC_TOBE_LABORATORY_REPORT'
// 二期实验查询/原始记录单
export const LABORATORY_SEC_LABERATORY_QUERY = 'LABORATORY_SEC_LABERATORY_QUERY'
// 二期实验查询/含油实验结果
export const LABORATORY_SEC_LABERATORY_CONTAINS_OIL_RESULT = 'LABORATORY_SEC_LABERATORY_CONTAINS_OIL_RESULT'
// 二期实验查询/实验报告单
export const LABORATORY_SEC_LABERATORY_SEARCH_REPORT = 'LABORATORY_SEC_LABERATORY_SEARCH_REPORT'
// 二期物检定等中心值
export const LABORATORY_SEC_CENTRAL_VALUE = 'LABORATORY_SEC_CENTRAL_VALUE'
// 二期物检报表/日表报审核
export const LABORATORY_SEC_REOPRT_DAYLY_AUDIT = 'LABORATORY_SEC_REOPRT_DAYLY_AUDIT'
// 二期物检报表/日报表
export const LABORATORY_SEC_REOPRT_DAYLY = 'LABORATORY_SEC_REOPRT_DAYLY'
// 二期物检报表/月表报
export const LABORATORY_SEC_REOPRT_MONTHLY = 'LABORATORY_SEC_REOPRT_MONTHLY'
// 二期物检报告/周报表
export const LABORATORY_SEC_REPORT_WEEKLY = 'LABORATORY_SEC_REPORT_WEEKLY'
// 二期数据导入/设备管理
export const LABORATORY_SEC_ACQUISITION_EQUIPMENT_MANAGEMENT = 'LABORATORY_SEC_ACQUISITION_EQUIPMENT_MANAGEMENT'
// 二期数据导入/数据导入
export const LABORATORY_SEC_ACQUISITION_DATA_IMPORT = 'LABORATORY_SEC_ACQUISITION_DATA_IMPORT'
// 二期仪器管理/仪器分类
export const LABORATORY_SEC_INSTRUMENT_CLASSIFY = 'LABORATORY_SEC_INSTRUMENT_CLASSIFY'
// 二期仪器管理/仪器台帐
export const LABORATORY_SEC_INSTRUMENT_BOOK = 'LABORATORY_SEC_INSTRUMENT_BOOK'
// 二期仪器管理/仪器校准
export const LABORATORY_SEC_INSTRUMENT_ADJUSTING = 'LABORATORY_SEC_INSTRUMENT_ADJUSTING'
// 二期仪器管理/仪器维修
export const LABORATORY_SEC_INSTRUMENT_REPAIR = 'LABORATORY_SEC_INSTRUMENT_REPAIR'
// 二期仪器管理/仪器报废
export const LABORATORY_SEC_INSTRUMENT_SCRAP = 'LABORATORY_SEC_INSTRUMENT_SCRAP'
// 二期材料管理/材料分类
export const LABORATORY_SEC_MATERIAL_CLASSIFY = 'LABORATORY_SEC_MATERIAL_CLASSIFY'
// 二期材料管理/材料
export const LABORATORY_SEC_MATERIAL = 'LABORATORY_SEC_MATERIAL'
// 二期材料管理/材料入库
export const LABORATORY_SEC_MATERIAL_INBOUND = 'LABORATORY_SEC_MATERIAL_INBOUND'
// 二期材料管理/材料出库
export const LABORATORY_SEC_MATERIAL_OUTBOUND = 'LABORATORY_SEC_MATERIAL_OUTBOUND'
// 二期材料管理/材料统计
export const LABORATORY_SEC_MATERIAL_STATISTICS = 'LABORATORY_SEC_MATERIAL_STATISTICS'
// 二期人员管理/人员台帐
export const LABORATORY_SEC_PERSON_BOOK = 'LABORATORY_SEC_PERSON_BOOK'
// 二期人员管理/培训管理
export const LABORATORY_SEC_PERSON_TRAIN = 'LABORATORY_SEC_PERSON_TRAIN'
// 二期人员管理/奖惩管理
export const LABORATORY_SEC_PERSON_REWARD_AND_PUNISHMENT = 'LABORATORY_SEC_PERSON_REWARD_AND_PUNISHMENT'
// 人员管理 -- 工作量统计
export const LABORATORY_PERSONNEL_MANAGEMENT_WORKLOAD_STATISTICS = 'LABORATORY_PERSONNEL_MANAGEMENT_WORKLOAD_STATISTICS'

/** -------------------------------------------------------二期化检---------------------------------------------------------- */
// 化检/化检管理/参数管理
export const LABORATORY_CHEMICAL_DATAFIELD_MANAGE = 'LABORATORY_CHEMICAL_DATAFIELD_MANAGE'
// 化检管理/样品分类
export const LABORATORY_CHEMICAL_SAMPLE_MANAGE_SPLIT_GROUP = 'LABORATORY_CHEMICAL_SAMPLE_MANAGE_SPLIT_GROUP'
// 化检管理/样品部门
export const LABORATORY_CHEMICAL_SAMPLE_MANAGE_REGISTER = 'LABORATORY_CHEMICAL_SAMPLE_MANAGE_REGISTER'
// 化检管理/样品
export const LABORATORY_CHEMICAL_SAMPLE_MANAGE_SAMPLE = 'LABORATORY_CHEMICAL_SAMPLE_MANAGE_SAMPLE'
// 模板管理/原始记录单模板分类
export const LABORATORY_CHEMICAL_ORIGINAL_RECORDLIST_CLASSIFY = 'LABORATORY_CHEMICAL_ORIGINAL_RECORDLIST_CLASSIFY'
// 模板管理/原始记录单模板管理
export const LABORATORY_CHEMICAL_ORIGINAL_RECORDLIST_MANAGE = 'LABORATORY_CHEMICAL_ORIGINAL_RECORDLIST_MANAGE'
// 模板管理/实验报告单模板分类
export const LABORATORY_CHEMICAL_REPORTLIST_TEMPLATE_CLASSIFY = 'LABORATORY_CHEMICAL_REPORTLIST_TEMPLATE_CLASSIFY'
// 模板管理/实验报告单模板管理
export const LABORATORY_CHEMICAL_REPORTLIST_TEMPLATE_MANAGE = 'LABORATORY_CHEMICAL_REPORTLIST_TEMPLATE_MANAGE'
// 材料管理/材料分类
export const LABORATORY_CHEMICAL_MATERIAL_CLASSIFY = 'LABORATORY_CHEMICAL_MATERIAL_CLASSIFY'
// 材料管理/材料
export const LABORATORY_CHEMICAL_MATERIAL = 'LABORATORY_CHEMICAL_MATERIAL'
// 材料管理/材料入库
export const LABORATORY_CHEMICAL_MATERIAL_INBOUND = 'LABORATORY_CHEMICAL_MATERIAL_INBOUND'
// 材料管理/材料出库
export const LABORATORY_CHEMICAL_MATERIAL_OUTBOUND = 'LABORATORY_CHEMICAL_MATERIAL_OUTBOUND'
// 材料管理/材料统计
export const LABORATORY_CHEMICAL_MATERIAL_STATISTICS = 'LABORATORY_CHEMICAL_MATERIAL_STATISTICS'
// 仪器管理/仪器分类
export const LABORATORY_CHEMICAL_INSTRUMENT_CLASSIFY = 'LABORATORY_CHEMICAL_INSTRUMENT_CLASSIFY'
// 仪器管理/仪器台帐
export const LABORATORY_CHEMICAL_INSTRUMENT_BOOK = 'LABORATORY_CHEMICAL_INSTRUMENT_BOOK'
// 仪器管理/仪器校准
export const LABORATORY_CHEMICAL_INSTRUMENT_ADJUSTING = 'LABORATORY_CHEMICAL_INSTRUMENT_ADJUSTING'
// 仪器管理/仪器维修
export const LABORATORY_CHEMICAL_INSTRUMENT_REPAIR = 'LABORATORY_CHEMICAL_INSTRUMENT_REPAIR'
// 仪器管理/仪器报废
export const LABORATORY_CHEMICAL_INSTRUMENT_SCRAP = 'LABORATORY_CHEMICAL_INSTRUMENT_SCRAP'
// 人员管理/人员台帐
export const LABORATORY_CHEMICAL_PERSON_BOOK = 'LABORATORY_CHEMICAL_PERSON_BOOK'
// 人员管理/培训管理
export const LABORATORY_CHEMICAL_PERSON_TRAIN = 'LABORATORY_CHEMICAL_PERSON_TRAIN'
// 人员管理/奖惩管理
export const LABORATORY_CHEMICAL_SEC_PERSON_REWARD_AND_PUNISHMENT = 'LABORATORY_CHEMICAL_SEC_PERSON_REWARD_AND_PUNISHMENT'
// 人员管理/工作量统计
export const LABORATORY_CHEMICAL_PERSONNEL_MANAGEMENT_WORKLOAD_STATISTICS = 'LABORATORY_CHEMICAL_PERSONNEL_MANAGEMENT_WORKLOAD_STATISTICS'
// 实验任务/普通样品登记
export const LABORATORY_CHEMICAL_SAMPLE_REGISTER_REGISTER = 'LABORATORY_CHEMICAL_SAMPLE_REGISTER_REGISTER'
// 实验任务/日常任务
export const LABORATORY_CHEMICAL_SAMPLE_REGISTER_DAILY_TASKS = 'LABORATORY_CHEMICAL_SAMPLE_REGISTER_DAILY_TASKS'
// 实验任务/原始记录单
export const LABORATORY_CHEMICAL_TOBE_LABORATORY_ORIGINAL_RECORDLIST = 'LABORATORY_CHEMICAL_TOBE_LABORATORY_ORIGINAL_RECORDLIST'
// 实验任务/报告单
export const LABORATORY_CHEMICAL_TOBE_LABORATORY_REPORTLIST = 'LABORATORY_CHEMICAL_TOBE_LABORATORY_REPORTLIST'
// 实验任务/标样
export const LABORATORY_CHEMICAL_TOBE_LABORATORY_SAMPLE = 'LABORATORY_CHEMICAL_TOBE_LABORATORY_SAMPLE'
// 留样管理/留样管理
export const LABORATORY_CHEMICAL_SAMPLE_REGISTER_KEEP_MANAGE = 'LABORATORY_CHEMICAL_SAMPLE_REGISTER_KEEP_MANAGE'
// 实验结果/报告单
export const LABORATORY_CHEMICAL_LABERATORY_QUERY_REPORT = 'LABORATORY_CHEMICAL_LABERATORY_QUERY_REPORT'
// 实验结果/原始记录
export const LABORATORY_CHEMICAL_LABERATORY_QUERY_ORIGINAL_RECORDLIST = 'LABORATORY_CHEMICAL_LABERATORY_QUERY_ORIGINAL_RECORDLIST'
// 实验结果/标样
export const LABORATORY_CHEMICAL_LABERATORY_QUERY_SAMPLE = 'LABORATORY_CHEMICAL_LABERATORY_QUERY_SAMPLE'
// 报表统计/报告单月趋势图
export const LABORATORY_CHEMICAL_LABERATORY_REPORT_STATISTICS = 'LABORATORY_CHEMICAL_LABERATORY_REPORT_STATISTICS'
