// import * as common from './common'
import * as person from './employee'
import * as collect from './collect/inventory-management'
import * as device from './device'
import * as productInfo from './product-info'
import * as productPlan from './product-plan'
import * as dictionary from './dictionary'
import * as measurePrinting from './measure-printing'
import * as productionProcess from './production-process'
import * as board from './board'
import * as barCode from './bar-code'
import * as statement from './statement'
import * as other from './other'
export { person, collect, device, productInfo, productPlan, dictionary, productionProcess, measurePrinting, board, barCode, statement, other }
